environment:
  TWINE_PASSWORD:
    secure: M+qvYgRh05fEw6G9aglK4g==
  matrix:
  - BUILD_TYPE: "Debug"
  - BUILD_TYPE: "Release"
  - BUILD_TYPE: "Python36"
  - BUILD_TYPE: "Python35"
  - BUILD_TYPE: "Python27"
  global:
    PLATFORMTOOLSET: "v140"

install:
# Rename sh.exe as sh.exe in PATH interferes with MinGW.
- rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"

build_script:
- C:\Python36-x64\python.exe tools\install_appveyor.py

artifacts:
  - path: build\wheel\dist
    name: wheels
 
# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, or Microsoft Remote Desktop app in osx
#  use the login information that the line below prints into the log.
#on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

